# Generated by Django 4.2 on 2025-06-03 04:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('overview', models.TextField()),
                ('release_date', models.DateField()),
                ('country', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=50)),
                ('producer', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('genre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'movies',
            },
        ),
    ]
